name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['18.x', '20.x', '22.x']

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
          POSTGRES_DB: forumapi_test

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      # - name: installing package, migrate and test
      #   run: |
      #     npm install
      #     npm run migrate:test up
      #     npm run test
      - name: installing package
        run: |
          npm install
      - name: wait for postgres to be ready
        run: sleep 10
      - name: run migrate and test
        run: |
          npm run migrate:test up
          npm run test
        env:
          CI: true
          HOST: localhost
          PORT: 5000
          PGHOST: localhost
          PGPORT: 5432
          PGUSER: postgres
          PGPASSWORD: root
          PGDATABASE: forumapi_test
          ACCESS_TOKEN_KEY: secret
          REFRESH_TOKEN_KEY: terces
          ACCESS_TOKEN_AGE: 3600
